name: Build y Testing de proyecto .NET

on: 
  push:
    branches: [ 'master' ]
  pull_request:
    branches: ['master']
    
jobs:
  buildear-proyecto:
    runs-on: ubuntu-latest
    steps:
      # Descargar el repositorio en el Runner
      - uses: actions/checkout@v4

      - name: Instalando entorno de desarrollo .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
          cache: true
          cache-dependency-path: '**/package-lock.json'
      - name: Instalando dependenicas
        run:  dotnet restore --locked-mode
      - name: Buildeando solucioon
        run: dotnet build
      - name: Testeando proyecto
        run: dotnet test
