name: GitHub Actions Demo
run-name: ${{ github.actor }} esta probando GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 El job fue automaticamente activado por un evento ${{ github.event_name }}."
      - run: echo "🐧 Este job esta corriendo en un servidor de sistema operativo ${{ runner.os }} hosteado por GitHub!"
      - run: echo "🔎 El nombre de la branch es ${{ github.ref }} y tu repositio es ${{ github.repository }}."
      - name: Checando el codigo del repositorio
        uses: actions/checkout@v4
      - run: echo "💡 El repositorio ${{ github.repository }} ha sido clonado por el runner."
      - run: echo "🖥️ El workflow esta lista para probar tu codigo en el runner."
      - name: Enlistar archivos en el repositorio
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 El estatus de este job es ${{ job.status }}."
      - name: Crear carpeta si no existe
        run: if [ ! -d "/home/IDI/creando-otra-carpeta-con-el-runner" ]; then mkdir /home/IDI/creando-otra-carpeta-con-el-runner; fi

